#ifndef ERROR_H_
#define ERROR_H_

typedef enum {
    ERROR_COMMAND_NOT_FOUND,
    ERROR_INSUFFICIENT_ARGUMENTS,
    ERROR_CD_NO_SUCH_DIRECTORY,
    ERROR_ENVIRONMENT_VARIABLE_NOT_SET,
    ERROR_TOKENIZATION_FAILED,
    ERROR_UNTERMINATED_QUOTE,
    ERROR_PARSING_FAILED
} ErrorType;

void error(ErrorType errorType, const char* details);

#endif
